name: 'Deploy on Vercel'
description: 'Easily deploy your project on Vercel'
branding:
#icon: bookmark #TODO
#color: red
inputs:
  command:
    description: 'Command to execute to start vercel deployment'
    required: true
  deploy_alias:
    description: 'Enable alias feature in the vercel.json'
    required: false
    default: "true"
  failIfAliasNotLinked:
    description: 'If true, will throw an error (and crash CI) when there is an error about aliases link'
    required: false
    default: "false"
outputs:
  deployment-url:
    description: "Url deployed"
runs:
  using: 'node12'
  main: 'lib/main.js'
