name: 'Deploy on Vercel'
description: 'Easily deploy your project on Vercel'
branding:
#icon: bookmark #TODO
#color: red
inputs:
  command:
    description: 'Command to execute to start vercel deployment'
    required: true
  apply_domain_aliases:
    description: 'Enable alias feature in the vercel.json'
    required: false
    default: "true"
  failIfAliasNotLinked:
    description: 'If true, will throw an error (and crash CI) when there is an error about aliases link'
    required: false
    default: "false"
outputs:
  VERCEL_DEPLOYMENT_URL:
    description: "Url found in the output"
  VERCEL_DEPLOYMENT_DOMAIN:
    description: "Url without protocol declaration 'https://'"
  VERCEL_ALIASES_ERROR:
    description: "Errors if something went wrong with the aliases"
runs:
  using: 'node12'
  main: 'lib/main.js'
