name: 'Deploy on Vercel'
description: 'Easily deploy your project on Vercel'
branding:
  icon: box
  color: gray-dark
inputs:
  command:
    description: 'Command starting the vercel deployment'
    required: true
  applyDomainAliases:
    description: 'If true, will create Vercel aliases using the aliases specified in the vercel config file'
    required: false
    default: "true"
  failIfAliasNotLinked:
    description: 'If true, will throw an error (and crash CI) when there is an error about aliases link'
    required: false
    default: "false"
  extraAliases:
    description: 'List of additional aliases to create, will be added to the aliases specified in the vercel.json:aliases file'
    required: false
outputs:
  VERCEL_DEPLOYMENT_URL:
    description: "Full Vercel deployment url (parsed from the deployment logs), e.g: https://xxx.vercel.app"
  VERCEL_DEPLOYMENT_DOMAIN:
    description: "Url without the protocol declaration, e.g: xxx.vercel.app"
  VERCEL_ALIASES_ERROR:
    description: "(optional) Vercel errors during domain aliasing"
runs:
  using: 'node12'
  main: 'github-action-runtime/index.js'
