name: 'GitHub Action integration test'
on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  run-integration-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn # Install all dependencies
      - uses: ./
        with:
          # TODO Explain what this command does, it's unclear. It looks like it's an integration test for parsing the vercel output
          command: "yarn test:integration"
          applyDomainAliases: true
          failIfAliasNotLinked: false
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          # TODO Why is this necessary? Shouldn't it be an output? It's not supposed to be provided as input
          VERCEL_DEPLOYMENT_URL: "https://github-action-deploy-on-vercel-example.vercel.app/"

      - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""
