name: 'GitHub Action integration test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-integration-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          command: "yarn test:integration"
          apply_domain_aliases: true
          failIfAliasNotLinked: false
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_DEPLOYMENT_URL: "https://github-action-deploy-on-vercel-example.vercel.app/"

      - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""