name: 'GitHub Action deploy example'
on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  run-example-deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo '::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)'
        id: extract_branch

      - uses: ./
        with:
          command: "yarn deploy:example --token ${{ secrets.VERCEL_TOKEN }}"
          applyDomainAliases: true
          failIfAliasNotLinked: false
          extraAliases: >-
            github-action-deploy-on-vercel-${{ steps.extract_branch.outputs.branch }}.vercel.app,
            github-action-deploy-on-vercel-dynamic

        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""
      - run: "echo \"Created aliases ${{ env.VERCEL_ALIASES_CREATED }}\""
      - run: "echo \"Created aliases (full) ${{ env.VERCEL_ALIASES_CREATED_FULL }}\""

      - run: "echo \"Alias markdown generated: ${{ env.VERCEL_ALIASES_CREATED_URLS_MD }}\""
