name: 'GitHub Action deploy example'
on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  run-example-deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # extract branch name on branch push
      - name: Extract branch name (in case of push on branch)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      # extract branch name on pull request changes
      - name: Extract branch name (in case of changes on pull request)
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - uses: ./
        with:
          command: "yarn deploy:example --token ${{ secrets.VERCEL_TOKEN }}"
          applyDomainAliases: true
          failIfAliasNotLinked: false
          extraAliases: >-
            github-action-deploy-on-vercel-${{ env.BRANCH_NAME }}.vercel.app,
            github-action-deploy-on-vercel-dynamic.vercel.app,
            github-action-deploy-on-vercel-dynamic-test-limit-alias-length.vercel.app

        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""
      - run: "echo \"Created aliases ${{ env.VERCEL_ALIASES_CREATED }}\""
      - run: "echo \"Created aliases (full) ${{ env.VERCEL_ALIASES_CREATED_FULL }}\""

      - run: "echo \"Alias markdown generated: ${{ env.VERCEL_ALIASES_CREATED_URLS_MD }}\""
