# Summary:
# Test the GitHub Action using an integration test.
# Makes sure the GitHub Action works properly when running on a clean machine, without building anything (integration test).
# This integration test will break if the Vercel project or deployment are deleted, or if the VERCEl_TOKEN doesn't have access to the deployment url.
#
# See https://github.com/actions/checkout https://github.com/actions/checkout/releases/tag/v2

name: 'GitHub Action integration test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-integration-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          command: "yarn test:integration"
          apply_domain_aliases: true
          failIfAliasNotLinked: false
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_DEPLOYMENT_URL: "https://nrn-v2-mst-aptd-at-lcz-sty-c1.vercel.app"

      - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""