name: 'GitHub Action integration test'
on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  run-integration-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Installing node.js
        uses: actions/setup-node@v2 # Used to install node environment - https://github.com/actions/setup-node
        with:
          node-version: '12.x' # Use the same node.js version as the one Vercel's uses (currently node14.x)
      - uses: ./
        with:
          command: "yarn test:integration"
          applyDomainAliases: true
          failIfAliasNotLinked: false
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_DEPLOYMENT_URL: "https://github-action-deploy-on-vercel-example.vercel.app/"

      - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""
