name: 'GitHub Action deploy example'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-example-deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: "github-action-deploy-on-vercel" # act doesn't work without a specific path. @see https://github.com/nektos/act/issues/228
      - uses: ./
        with:
          command: "yarn deploy:example --token ${{ secrets.VERCEL_TOKEN }}"
          apply_domain_aliases: true
          failIfAliasNotLinked: false
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - run: "echo \"Found deployment url: ${{ env.VERCEL_DEPLOYMENT_URL }}\""